<?php
    define('HOSTNAME','http://flowercardvn.com/webservice/');
    define('BEST_SELLER','bestseller');
    define('BEST_SELLER_FILE','ws_client/bestseller.php');  
    define('PRODUCT_DETAIL','detailProduct');
    define('PRODUCT_DETAIL_FILE','ws_client/detailProduct.php');  
    define('PRODUCT_BY_CATEGORY','product');
    define('PRODUCT_BY_CATEGORY_FILE','ws_client/product.php');  
    define('CATEGORY','category');
    define('CATEGORY_FILE','ws_client/category.php');
    define('SHOPPINGCART','shoppingcart');
    define('SHOPPINGCART_FILE','ws_client/shoppingcart.php');
?>
